services:
    casm:
        image: coaas/casm:latest
        container_name: "casm"
        ports:
          - "8080:8080"
          - "4848:4848"
          - "8181:8181"
          - "9009:9009"
        environment:
            - CQE_BROKER=cqe
        links:
            - cqc:cqc
        depends_on:
            - cqc


    cqp:
        image: coaas/cqp:latest
        container_name: "cqp"
        ports:
          - "8585:8585"
        restart: always


    cqc:
        image: coaas/cqc:latest
        container_name: "cqc"
        ports:
          - "8484:8484"
        restart: always
        links:
            - cqp:cqp
            - sqem:sqem
        depends_on:
            - cqp
            - sqem

    sqem:
        image: coaas/sqem:latest
        container_name: "sqem"
        ports:
          - "8686:8686"
        restart: always
        depends_on:
          - mongodb
        links:
          - mongodb


    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=alex
          - MONGODB_PASS=contextstorage_17
        volumes:
          - /userlogin/data/db:/var/lib/data/db
        expose:
            - "27017"
        ports:
            - 27018:27017
        command: mongod --logpath=/dev/null # --quiet
            
    mongo-seed:
        build: ./mongo-seed
        restart: on-failure
        depends_on:
          - mongodb
        links:
          - mongodb